// DOM - Document Object Module
/*
  Window vs Document
  DOM vs BOM
  DOM Navigation
  Searching and getting Elements Reference

Window vs Document:
Window:
1.Window is the main container or we can say the global object and any operations related to entire browser window can be a part of window object.
2.All the members like objects,methods or properties. If they are the part of window object then we do not refer the window object.
3.Window has methods, properties and object. ex setTimeout() or setInterval() are the methods, where as Document is the object of the window and it also has a screen object with properties describing the physical display.
Document:
1.Whereas the DOM is the child of window object.
2.Where in the DOM we need to refer the document, if we want to use the document object, methods or properties.
3.Document is just the object of the global object that is window, which deals with the document, the HTML elements themselves.

USE DIAGRAMS TO EXPLAIN WINDOW GLOBAL OBJECT
                      Window
        DOM             BOM        JavaScript
     document         navigator      object
      <HTML>          screen         Array
  <body>  <head>      location       Function
 <a>  <p>             frames           ...
                      history
                      XML HttpRequest

   DOM
 - Document Object Module
 - Browser convert into document to html for access by javascript
 - Tree of Elements(Nodes) generated by Browser
 - JavaScript can manipulate DOM
 
 DOM tree of nodes   
 
 //dom navigation
//with the HTML DOM, you can navigate the node tree using node relationships = dom tree,
// it's looks like navigation

Navigating Between Nodes
You can use the following node properties to navigate between nodes with JavaScript:

parentNode
childNodes[nodenumber]
firstChild
lastChild
nextSibling
previousSibling

//dom node
//nodes
ELEMENT_NODE	1	<h1 class="heading">W3Schools</h1>
ATTRIBUTE_NODE	2	 class = "heading" (deprecated)
TEXT_NODE	3	W3Schools
COMMENT_NODE	8	<!-- This is a comment -->
DOCUMENT_NODE	9	The HTML document itself (the parent of <html>)
DOCUMENT_TYPE_NODE	10	<!Doctype html>

// document.getElementById("id").firstChild.nodeValue;
// document.getElementById("id").firstChild.nodeType;


*/
